apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-eqse
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-eqse
    app.kubernetes.io/part-of: test-app-emjn
  name: test-component-eqse
  namespace: build-e2e-txte-tenant
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: test-component-eqse
    weight: 100
status: {}
